### PR TITLE
Configure default population per class

### PR DESCRIPTION
**Pull request by palkan**
### What is the purpose of this pull request?

Follow-up for #34.

Instead of a global option, I propose moving this configuration to models (so we can explicitly control, which classes need this behavior):

```ruby
class ApplicationRecord < ActiveRecord::Base
  self.store_attribute_unset_values_fallback_to_default = true

  store_attribute :extra, :color, :string, default: "grey"
end

user = User.create!(extra: {})
# without the fallback
user.color #=> nil
# with fallback
user.color #=> "grey"
``` 

### Checklist

- [x] I've added tests for this change
- [x] I've added a Changelog entry
- [x] I've updated a documentation (Readme)

### CODE REVIEW

**Comment by palkan** [comment]
@markedmondson Please, take a look.

**Comment by markedmondson** [comment]
@palkan looks good to me!

**Comment by Alan-Marx** [comment]
@palkan - If the goal is to have more fine grained control than that provided by the global configuration option, would it make sense to configure this option per `store_attribute` as opposed to per model?

**Comment by palkan** [comment]
> would it make sense to configure this option per store_attribute as opposed to per model?

Not sure. I see how per-model approach can be helpful; the primary use-case is to make it global for the project (`ApplicationRecord`), so you always can rely on default values. You just configure it once and for all. 
But per-attribute approach introduces additional complexity: you need to take this option into account when reasoning about store attributes. And I can't come up with a use case when you want some attributes behave differently from another with regards to defaults.

**Pull request merged**
